In [2]:
import jax
from jax import numpy as jnp

In [4]:
x = jnp.arange(12)
x

Array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [5]:
x.size

12

In [6]:
x.shape

(12,)

In [7]:
X = x.reshape(3, 4)
X

Array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [8]:
jnp.zeros((2, 3, 4))

Array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [9]:
jnp.ones((2, 3, 4))

Array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [10]:
jax.random.split(jax.random.PRNGKey(0), (3, 4))

Array([[[1797259609, 2579123966],
        [ 928981903, 3453687069],
        [4146024105, 2718843009],
        [2467461003, 3840466878]],

       [[2285895361,  433833334],
        [1524306142, 1887795613],
        [3792494674, 2909014575],
        [2716826189,  292468403]],

       [[2292653872,  931858003],
        [ 823147153,  450340679],
        [3668660785,  652965180],
        [ 255289810,  156206175]]], dtype=uint32)

In [11]:
jnp.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

Array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)